export const FETCH_TOUR_SUCCESS = 'FETCH_TOUR_SUCCESS';
export const FETCH_TOUR_START = 'FETCH_TOUR_START';
export const FETCH_TOUR_FAILED = 'FETCH_TOUR_FAILED';
export const SET_TOUR_LIST = 'SET_TOUR_LIST';

export const REVIEW_TOUR_START = 'REVIEW_TOUR';
export const REVIEW_TOUR_SUCCESS = 'REVIEW_TOUR_SUCCESS';
export const REVIEW_TOUR_FAILED = 'REVIEW_TOUR_FAILED';

export const FETCH_TOUR__SIMILAR_FAILED = 'FETCH_TOUR__SIMILAR_FAILED';
export const SET_TOUR_SIMILAR_LIST = 'SET_TOUR_SIMILAR_LIST';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGIN = 'AUTH_LOGIN';

export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_LOAD_USER = 'AUTH_LOAD_USER';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_BLOG_SUCCESS = 'FETCH_BLOG_SUCCESS';
export const FETCH_BLOG_START = 'FETCH_BLOG_START';
export const FETCH_BLOG_FAILED = 'FETCH_BLOG_FAILED';
export const SET_BLOG_LIST = 'SET_BLOG_LIST';
export const COMMENT_BLOG = '';
export const DELETE_COMMENT_BLOG = '';
export const LIKE_BLOG = '';
export const UNLIKE_BLOG = '';
export const FETCH_BLOG_DETAIL_FAILED = 'FETCH_BLOG_DETAIL_FAILED';
export const SET_BLOG_DETAIL = 'SET_BLOG_DETAIL';

export const FETCH_DESTINATION_SUCCESS = 'FETCH_DESTINATION_SUCCESS';
export const FETCH_DESTINATION_START = 'FETCH_DESTINATION_START';
export const FETCH_DESTINATION_FAILED = 'FETCH_DESTINATION_FAILED';
export const SET_DESTINATION_LIST = 'SET_DESTINATION_LIST';

export const FETCH_REVIEW_SUCCESS = 'FETCH_REVIEW_SUCCESS';
export const FETCH_REVIEW_START = 'FETCH_REVIEW_START';
export const FETCH_REVIEW_FAILED = 'FETCH_REVIEW_FAILED';
export const SET_REVIEW_LIST = 'SET_REVIEW_LIST';
export const CHECK_USER_REVIEW = 'CHECK_USER_VIEW';
export const SET_USER_REVIEW = 'SET_USER_REVIEW';

export const FETCH_TOUR_DETAIL_SUCCESS = 'FETCH_TOUR_DETAIL_SUCCESS';
export const FETCH_TOUR_DETAIL_FAILED = 'FETCH_TOUR_DETAIL_FAILED';
export const SET_TOUR_DETAIL = 'SET_TOUR_DETAIL';

// export const SET_SEARCH_TOUR = 'SET_SEARCH_TOUR';

export const FETCH_REVIEW_TOUR_LIST_FAILED = 'FETCH_REVIEW_TOUR_LIST_FAILED';
export const SET_REVIEW_TOUR_LIST = 'SET_REVIEW_TOUR_LIST';
export const LOAD_MORE_REVIVIEW_TOUR_LIST = 'LOAD_MORE_REVIVIEW_TOUR_LIST';
export const SET_REVIEW_TOUR_LIST_START = 'SET_REVIEW_TOUR_LIST_START';

export const SET_BOOKING_INFO = 'SET_BOOKING_INFO';
export const CREATE_BOOKING = 'CREATE_BOOKING';
export const CREATE_BOOKING_FAILED = 'CREATE_BOOKING_FAILED';

export const REGISTER_EMAIL_PROMOTION = 'REGISTER_EMAIL_PROMOTION';
export const REGISTER_EMAIL_PROMOTION_FAILED =
  'REGISTER_EMAIL_PROMOTION_FAILED';

export const SET_PROMOTION_LIST = 'SET_PROMOTION_LIST';
export const FETCH_PROMOTION_FAILED = 'FETCH_PROMOTION_FAILED';

export const FETCH_PROMOTION_DETAIL_FAILED = 'FETCH_PROMOTION_DETAIL_FAILED';
export const SET_PROMOTION_DETAIL = 'SET_PROMOTION_DETAIL';
